import pandas as pd

country_region = {
    # Middle East (including North Africa)
    "Algeria": "Middle East",
    "Bahrain": "Middle East",
    "Cyprus": "Middle East",
    "Egypt": "Middle East",
    "Iran": "Middle East",
    "Iraq": "Middle East",
    "Israel": "Middle East",
    "Jordan": "Middle East",
    "Kuwait": "Middle East",
    "Lebanon": "Middle East",
    "Libya": "Middle East",
    "Morocco": "Middle East",
    "Qatar": "Middle East",
    "Saudi Arabia": "Middle East",
    "State of Palestine": "Middle East",
    "Sudan": "Middle East",
    "Syria": "Middle East",
    "Tunisia": "Middle East",
    "Turkey": "Middle East",
    "United Arab Emirates": "Middle East",
    # Europe
    "Austria": "Europe",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Bosnia and Herzegovina": "Europe",
    "Bulgaria": "Europe",
    "Croatia": "Europe",
    "Czech Republic": "Europe",
    "Denmark": "Europe",
    "Estonia": "Europe",
    "Finland": "Europe",
    "France": "Europe",
    "Georgia": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "Hungary": "Europe",
    "Italy": "Europe",
    "Latvia": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Monaco": "Europe",
    "Netherlands": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Republic of Ireland": "Europe",
    "Romania": "Europe",
    "Russia": "Europe",
    "Serbia": "Europe",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Ukraine": "Europe",
    "United Kingdom": "Europe",
    # Oceania
    "Australia": "Oceania",
    "Fiji": "Oceania",
    "New Zealand": "Oceania",
    "Papua New Guinea": "Oceania",
    "Tuvalu": "Oceania",
    # North America
    "Barbados": "North America",
    "Canada": "North America",
    "Costa Rica": "North America",
    "Cuba": "North America",
    "Dominican Republic": "North America",
    "El Salvador": "North America",
    "Guatemala": "North America",
    "Haiti": "North America",
    "Honduras": "North America",
    "Jamaica": "North America",
    "Mexico": "North America",
    "Nicaragua": "North America",
    "Panama": "North America",
    "Trinidad and Tobago": "North America",
    "United States of America": "North America",
    # South America
    "Argentina": "South America",
    "Bolivia": "South America",
    "Brazil": "South America",
    "Chile": "South America",
    "Colombia": "South America",
    "Ecuador": "South America",
    "Paraguay": "South America",
    "Peru": "South America",
    "Suriname": "South America",
    "Uruguay": "South America",
    "Venezuela": "South America",
    # Asia
    "Afghanistan": "Asia",
    "Azerbaijan": "Asia",
    "Bangladesh": "Asia",
    "Hong Kong": "Asia",
    "India": "Asia",
    "Indonesia": "Asia",
    "Japan": "Asia",
    "Kazakhstan": "Asia",
    "Kyrgyzstan": "Asia",
    "Malaysia": "Asia",
    "Myanmar": "Asia",
    "Nepal": "Asia",
    "North Korea": "Asia",
    "Pakistan": "Asia",
    "People's Republic of China": "Asia",
    "Philippines": "Asia",
    "Singapore": "Asia",
    "South Korea": "Asia",
    "Taiwan": "Asia",
    "Thailand": "Asia",
    "Uzbekistan": "Asia",
    # Africa (sub-Saharan only)
    "Equatorial Guinea": "Africa",
    "Ethiopia": "Africa",
    "Ghana": "Africa",
    "Kenya": "Africa",
    "Nigeria": "Africa",
    "Republic of the Congo": "Africa",
    "Senegal": "Africa",
    "South Africa": "Africa",
    "Uganda": "Africa",
}

csv_file_path = "./data/clean_data/output.csv"
df = pd.read_csv(csv_file_path)

df["region"] = df["country"].map(country_region)

df.to_csv(csv_file_path, index=False)
